apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: mypod
spec:
  containers:
  - name: mycontainer
    image: liondr123/swarmtest:node1
    ports:
    - containerPort: 8085
    resources: {}
